import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import WalletModalProvider from "@/components/providers/WalletModalProvider";
import ConvexClientProvider from "@/components/providers/ConvexClientProvider";
import EmbeddedWalletProvider from "@/components/providers/EmbeddedWalletProvider";
import WalletDrawerProvider from "@/components/providers/WalletDrawerProvider";
import { NotificationPanelProvider } from "@/components/providers/NotificationPanelProvider";
import NotificationsPanel from "@/components/NotificationsPanel";
import { PrepStreamProvider } from "@/components/providers/PrepStreamProvider";
import { CameraPermissionsProvider } from "@/components/providers/CameraPermissionsProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        suppressHydrationWarning
      >
        <ConvexClientProvider>
          <EmbeddedWalletProvider>
            <WalletModalProvider>
              <WalletDrawerProvider>
                <NotificationPanelProvider>
                  <PrepStreamProvider>
                    <CameraPermissionsProvider>
                      {children}
                      <NotificationsPanel />
                    </CameraPermissionsProvider>
                  </PrepStreamProvider>
                </NotificationPanelProvider>
              </WalletDrawerProvider>
            </WalletModalProvider>
          </EmbeddedWalletProvider>
        </ConvexClientProvider>
      </body>
    </html>
  );
}
